### ISSUE TITLE
What about the browser console?

### ISSUE THREAD

**Issue by cfjedimaster** [dwkns/eleventy-plugin-console-plus#1]
Would this make sense - instead of outputting to terminal or the browser *display*, it would output to the console, ie:

<script>console.log(the var)</script>

This way I could see debug output and _not_ have it impact the layout of my site.

**Comment by dwkns** [comment]
Hmmmm. It probably could do this. It would mean injecting some JS into the page. You probably wouldn’t get colourisation and you might lose some formatting. And would need to check what happens if you have multiple logs in a single page. 

But yeah. Could work. Let me have a look into it.

**Comment by dwkns** [comment]
Added in version 0.1.0 via https://github.com/dwkns/eleventy-plugin-console-plus/pull/2

**Comment by cfjedimaster** [comment]
FYI, I see a screenshot in the readme, but don't see logToBrowserConsole documented there. Did I miss it?

**Comment by dwkns** [comment]
Whoops.
The feature is on by default; I just missed it from the README. 
Changed in v0.1.1
https://www.npmjs.com/package/eleventy-plugin-console-plus
